src/components/CredentialRequestsEditor/components/DataFieldMulti.tsx
src/components/CredentialRequestsEditor/components/DataFieldOptionType.tsx

Just fix some typescript issues
[Ticket]()

chore: fix typescript issues

---

src/components/When.tsx
src/components/terms/AcceptTermsNotice.tsx
src/components/terms/LegalLink.tsx

feat: Components When, and terms
[Ticket]()

feat: Components When, and terms

---

package.json
src/index.ts
src/utils/index.ts
src/validations/fragments/index.ts
src/validations/index.ts

fix: index and exports

---

src/hooks/index.ts
src/hooks/useCallbackRef.ts
src/hooks/useDisclosure.ts

feat: Add useDisclosure hook
[Ticket]()

feat: Add useDisclosure hook

---

src/components/Image.tsx

chore: fix image export

---

src/validations/index.ts
src/validations/unix.schema.ts

Add unix schema to be exported
[Ticket]()

feat: add unix-schema to index

---

src/components/form/DateInput.tsx

Fix date input controlled state by observing parent's value changes

fix: date input controlled value state

---

src/components/form/DateInput.tsx
src/utils/date.ts

rename date method and remove unused ones
[Ticket]()
renamed the name of a method. It was wrong
Also removed unused methods

feat: rename date method and remove unused ones

---

package-lock.json
package.json
src/components/QRCodeDisplay/index.tsx
src/components/index.ts
src/hooks/index.ts
src/hooks/useQRCode.ts
src/stories/components/QRCodeDisplay.stories.tsx

Ads QR code display component and hook.
[Ticket]()
- add new component
- add new hook
Locally using story.

feat: add qr code display component

---

.gitignore
package-lock.json
package.json
tsconfig.json
vite.config.ts

Allows to bundle shared-ui deps and run pre-releases for testing purposes
[Ticket]()

Chore Bundler and prerelease script

---

README.md
vite.config.ts

Import the package.json peerDeps and add it to external packages config into vite
[Ticket]()

chore: automatic package external deps

---

.npmignore

adds npmignore so it publishes the dist folder
[Ticket]()

chore: adds npmignore so it publishes the dist folder

---

package-lock.json
package.json

update package name to include 'public'
[Ticket]()

chore: update package name to include 'public'

---

src/components/form/OTPInput.tsx

- fix: allow to paste on otp input
- refactor: remove unused style
[Ticket]()
- updated otp input
Locally.

fix paste otp input

---

src/components/Snackbar/index.tsx

remove unused props from CustomAlertComponent to eliminate warnings
[Ticket]()

Fix snackbar

---

src/styles/theme.ts

Remove maxWidth for alert.
[Ticket]()
- updated theme
Locally.

fix: remove max width

---

README.md

Adds publish workflow badge status.
[Ticket]()
- updated readme
Locally.

chore: add ci badge

---

README.md

refactor: replace fury.io to shields.io

---

README.md

Remove Remix reference in the readme.
[Ticket]()

chore: remove rmeix quotation

---

.eslintrc.json
README.md
package-lock.json
package.json
src/components/animation/Counter.tsx
src/components/animation/index.ts
src/components/animation/motions.ts
src/hooks/useOnClickOutside.ts
src/stories/components/animation/Counter.stories.tsx
src/stories/hooks/useOnClickOutside.stories.tsx
vite.config.mts

Added new animation functionality and hooks to enhance component interactivity and user experience.
[Ticket]()
- Added new animation capabilities
- Implemented new custom hook for animation handling
- Verified animations work correctly in local environment
- Tested hook functionality across different components

new modules

---

src/hooks/index.ts
src/hooks/useDebounceValue.ts
src/hooks/useIntersectionObserver.ts
src/hooks/useScript.ts
src/hooks/useThrottle.ts
src/hooks/useToggle.ts
src/hooks/useWindowScroll.ts
src/hooks/useWindowSize.ts
src/stories/hooks/useDebounceValue.stories.tsx
src/stories/hooks/useIntersectionObserver.stories.tsx
src/stories/hooks/useScript.stories.tsx
src/stories/hooks/useThrottle.stories.tsx
src/stories/hooks/useToggle.stories.tsx
src/stories/hooks/useWindowScroll.stories.tsx
src/stories/hooks/useWindowSize.stories.tsx

Added a collection of custom React hooks to enhance component functionality and code reusability. These hooks provide common functionality like debouncing, throttling, window management, and intersection observation.
[Ticket]()
- **useDebounceValue**: Debounces value updates with configurable delay
- **useScript**: Manages external script loading with status tracking
- **useThrottle**: Limits value update frequency
- **useToggle**: Manages boolean toggle state
- **useWindowScroll**: Tracks and controls window scroll position
- **useWindowSize**: Tracks window dimensions
- **useIntersectionObserver**: Tracks element visibility using Intersection Observer API
Locally.

add modules

---

src/styles/theme.ts

Update menu text size.
[Ticket]()
Updated the theme
Locally

refactor: add font size to menu text

---

src/hooks/index.ts

Exports missing hooks.
[Ticket]()
- updated hooks index
locally.

fix: export missing modules

---

src/components/buttons/LinkButton.tsx
src/components/buttons/TextButton.tsx

Use theme default size.
[Ticket]()
- updated buttons size
Locally.

fix: use theme as default

---

package-lock.json
package.json
src/components/form/DateRangeInput/index.tsx
src/components/form/DateRangeInput/react-datepicker.css
src/components/form/DateRangeInput/style.ts
src/components/form/index.ts
src/stories/components/form/DateRangeInput.stories.tsx
src/types/css.d.ts

Adds date range input component.
[Ticket]()
- add new component
Locally.

feat: add date range input

---

src/components/form/TimezoneInput/index.tsx
src/components/form/TimezoneInput/timezones.json
src/stories/components/form/TimezoneInput.stories.tsx

Added comprehensive Storybook documentation for the TimezoneInput component's props, improving component usage clarity and developer experience.
[Ticket](https://trello.com/c/placeholder)
- Added `argTypes` documentation for the `value` prop with description, control type, and type information
- Added `argTypes` documentation for the `onChange` prop with description and type information
- Added the `component` property to properly connect TimezoneInput to Storybook
- Formatted code according to project style guidelines with proper comma placement and line breaks
Locally.

feat: add timezone select input

---

src/components/form/index.ts
src/stories/components/form/TimezoneInput.stories.tsx

Fixes export the timezone input.
[Ticket]()
- updated form index
Locally.

fix: exports timezone input

---

src/components/form/TimezoneInput/index.tsx

Remove box from render.
[Ticket]()
- updated input render
Locally.

fix: remove box from render

---

package-lock.json
package.json
src/components/chart/SeriesChartLegend/index.tsx
src/stories/components/chart/SeriesChartLegend.stories.tsx

Refactored chart legend component and moved chart-related dependencies to peer dependencies.
[Ticket]()
- Renamed [Legend](cci:1://file:///Users/iagormoraes/Desktop/projects/UnumID/shared-ui-elements/src/components/chart/ChartLegend/index.tsx:130:0-156:1) component to [SeriesChartLegend](cci:1://file:///Users/iagormoraes/Desktop/projects/UnumID/shared-ui-elements/src/components/chart/ChartLegend/index.tsx:130:0-156:1) for better clarity
- Added type safety improvements to the component
- Moved `decimal.js` and `recharts` from direct dependencies to peer dependencies with version constraints
- Improved null safety in entry total calculations
- Created proper component story structure under `src/stories/components/chart`

feat: add series chart legend

---

src/components/chart/SeriesChart/index.tsx
src/stories/components/chart/SeriesChart.stories.tsx
src/stories/components/chart/SeriesChartLegend.stories.tsx
src/utils/date.ts

Created SeriesChart component and stories, moved chart-related dependencies to peer dependencies, and improved type safety across chart components.
[Ticket]()
- Created new [SeriesChart](cci:1://file:///Users/iagormoraes/Desktop/projects/UnumID/shared-ui-elements/src/components/chart/SeriesChart/index.tsx:37:0-118:1) component for displaying time series data
- Created stories for [SeriesChart](cci:1://file:///Users/iagormoraes/Desktop/projects/UnumID/shared-ui-elements/src/components/chart/SeriesChart/index.tsx:37:0-118:1) and `SeriesChartLegend` components
- Moved `decimal.js` and `recharts` from direct dependencies to peer dependencies
- Added type safety improvements to chart components:
- Added proper TypeScript interfaces for chart data structures
- Improved null safety in data …

feat: add series chart

---

src/components/chart/index.ts
src/stories/components/chart/SeriesChart.stories.tsx
src/stories/components/chart/SeriesChartLegend.stories.tsx

Exports chart modules.
[Ticket]()
- added chart index
Locally.

fix: export modules

---

src/components/chart/SeriesChartLegend/index.tsx

Remove console log.
[Ticket]()
- remove log
Locally.

fix: remove log

---

src/components/form/DateRangeInput/index.tsx
src/components/form/DateRangeInput/style.ts

Add support to seconds in input.
[Ticket]()
- updated range input pattern
Locally.

fix: add seconds to input

---

src/components/chart/SimpleBarChart/index.tsx

fix: enforce boolean

---

src/components/chart/PieChart/index.tsx
src/components/chart/PieChart/renderActiveShape.tsx
src/components/chart/PieChart/renderNeedle.tsx
src/components/chart/SimpleLegend/index.tsx
src/stories/components/chart/PieChart.stories.tsx

Enhances the PieChart component with a needle indicator feature and improved customization options, allowing for better visualization of specific values within the chart's range.
[Ticket]()
- Added needle indicator feature to visually point to specific values on the chart
- Extracted rendering logic into separate files for better code organization:
- `renderActiveShape.tsx` for active segment visualization
- `renderNeedle.tsx` for needle indicator rendering
- Added new customization props:
- `legendToggle` for interactive legend functionality
- `valuePercentage` to toggle percentage display
- `needleVisible` and `needleValue` for needle indicator control
- `needleColor` for customizing needle appearance
- Improved value formatting with locale-aware number formatting
- Enhanced chart …

feat(PieChart): add needle indicator and enhance chart customization

---

src/components/chart/PieChart/index.tsx
src/components/chart/PieChart/renderActiveShape.tsx
src/components/chart/PieChart/renderNeedle.tsx
src/components/chart/RiskScorePieChart/index.tsx
src/components/chart/index.ts
src/stories/components/chart/PieChart.stories.tsx
src/stories/components/chart/RiskScorePieChart.stories.tsx

Implements a new risk score pie chart component and refactors the existing gauge component to improve its visual presentation and prop naming.
[Ticket]()
- Added new risk score pie chart component for enhanced data visualization
- Refactored gauge component to remove pointer for cleaner design
- Improved prop naming for better code clarity
- Added value prefix placeholder for more flexible value formatting
Locally.

risk score chart

---

src/components/chart/RiskScoreBarChart/index.tsx

Updated risk score terms.
[Ticket]()

refactor: update terms

---

src/components/chart/ErrorCodesChart/index.tsx

Updates the Error Codes Chart component to make the threshold configurable, enhancing its flexibility for different use cases.
[Ticket]()
- feat: make threshold configurable (81e00ad)
- Added configuration option for threshold values in the Error Codes Chart component
Locally.

feat: make threshold configurable

---

src/components/form/OneClickForm/components/DataField/inputs/DataFieldPhoneInput.tsx

Fix SSR form by ensuring window object is accessed only on the client side through appropriate React hooks.
[Ticket]()
- [8e13f2f] fix: access window within client side hook
- Modified form component to properly handle window object access in SSR context
Locally.

fix: access window within client side hook

---

src/components/CredentialRequestsEditor/utils/buildDataFieldValue.ts

Remove null from return type.
[Ticket]()
- updated build data field value module
Locally.

fix: remove null type

---

src/components/chart/SeriesChart/index.tsx
src/components/chart/SeriesChartLegend/index.tsx
src/stories/components/chart/SeriesChart.stories.tsx
src/stories/components/chart/SeriesChartLegend.stories.tsx

support integration type on 1-click percentage chart
[Ticket]()
local storybook

feat: support integration type on 1-click percentage chart

---

src/components/chart/monthly-billable-signups/MonthlyBillableSignupsTable.tsx

call EmptyChartSection and LoadingChartSection
[Ticket]()

chore: call EmptyChartSection and LoadingChartSection

---

src/components/chart/monthly-billable-signups/index.ts

fix: import name

---

vite.config.mts

Expose utils/phone modules.
[Ticket]()

chore: export phone utils

---

src/components/chart/OneClickOverTimeChart/OneClickTimeSeriesDataMapper.ts

remove default color and integration type checking
[Ticket]()

fix: remove default color and integration type checking

---

package-lock.json
package.json
src/components/chart/OneClickOverTimeChart/OneClickTimeSeriesDataMapper.ts

add optional param to filter out zero values
[Ticket]()
with the dashboard

feat: add optional param to filter out zero values

---

src/components/animation/AnimatedHeight.tsx
src/components/animation/index.ts
src/stories/components/animation/AnimatedHeight.stories.tsx

Add AnimatedHeight component that smoothly animates height changes when content is added or removed. This component is useful for collapsible sections and dynamic content areas.
[Ticket]()
- 4f948b4: Add AnimatedHeight component with the following:
- New AnimatedHeight component using framer-motion for smooth height transitions
- Story demonstrating the component with toggle functionality
- Export the component through animation/index.ts
- Check the Storybook stories under Components/Animation/AnimateHeight
- Test the toggle visibility functionality to ensure smooth height transitions
- Verify the component works with different content sizes

chore: add animated height component

---

package-lock.json
package.json
src/components/BrandFilterInput/BrandFilterInput.hook.ts
src/components/BrandFilterInput/index.tsx
src/components/chart/SeriesPercentageChart/index.tsx
src/utils/uuidColor.ts

Remove default brand limit for brand filter
[Ticket]()

Remove default brand limit for brand filter

---

src/components/chart/ErrorCodesChart/index.tsx
src/components/chart/ReasonCodesChart/index.tsx
src/components/chart/RiskScoreBarChart/index.tsx
src/components/chart/RiskScorePieChart/index.tsx
src/stories/components/chart/ErrorCodesChart.stories.tsx
src/stories/components/chart/ReasonCodesChart.stories.tsx
src/stories/components/chart/RiskScoreBarChart.stories.tsx
src/stories/components/chart/RiskScorePieChart.stories.tsx

Refactored charts to handle data loading states and improved code organization by removing unused code and updating props interface.
[Ticket]()
- [d451881] Removed unused code and improved code organization in RiskScorePieChart
- [1f7db71] Added data loading state handling to charts with loading, empty, and fetching states
- [cfb3906] Updated error and reason codes chart to receive data load state via props
- Improved documentation and examples in Storybook stories
- Verify all chart states in Storybook:
- Default state with data
- Loading state
- Empty state
- Fetching state
- With legend label
- Check that the charts properly handle all data loading scenarios
- Ensure proper display of loading and empty states
- Verify that the fetching state shows correct opacity

Refactor existing charts

---

src/components/verified/index.ts

Export OneClickPoweredByVerified.
[Ticket]()
- updated verified index file
Locally.

fix: export missing component

---

src/components/form/PhoneInput.tsx
src/stories/components/form/PhoneInput.stories.tsx

Add support to onBlur event.
[Ticket]()
- add onBlur event
Locally.

feat: support onBlur

---

src/components/verified/OneClickPoweredByVerified.tsx
src/stories/utils/phone.stories.tsx

Document phone utils and minor svg prop fix.
[Ticket]()
- fix the stroke width to JSX
- create phone utils stories
Locally.

chore: document phone utils

---

src/components/form/OTPInput.tsx

Fix sync of input props with error.
[Ticket]()
- updated input props dependency array
Locally.

fix(OTPInput): sync props error

---

src/styles/theme.ts

Adjusted input sizes and label positioning in the theme to ensure proper centering and consistent alignment across components.
[Ticket]()
- [570678d] fix(theme): Adjust input sizes and label to center it seamlessly
- Verified label positioning and centering in various input components
- Tested across different viewport sizes to ensure responsive behavior

fix(theme): Adjust input sizes and label to center it seamlessly

---

src/components/chart/ErrorCodesChart/index.tsx
src/components/chart/ReasonCodesChart/index.tsx

- Removed unhealthy threshold reference line from error codes chart
- Removed unhealthy threshold reference line from reason codes chart

feat: remove unhealthy threshold from error codes chart

---

package-lock.json
package.json
src/components/BrandFilterInput/index.tsx

Debounce values before calling on change. Also add sx as props
[Ticket]()
storybook local

Fix multi brand component to debounce values

---

src/components/chart/SeriesPercentageChart/index.tsx
src/components/chart/SeriesPercentageChartLegend/index.tsx

feat: add legend to percentage chart
feat: add legend to percentage chart
Access [this component](http://localhost:6006/?path=/story/charts-oneclickpercentagechart--default) while running storybook.

feat: add legend to percentage chart

---

src/components/form/DateRangeInput/style.ts
src/components/form/TimezoneInput/index.tsx

fix: increase input width to deal with new font sizes
[Ticket]()
storybook

fix: increase input width to deal with new font sizes

---

src/components/chart/NoRiskSignalsPermissionSection/index.tsx
src/components/chart/ReasonCodesChart/index.tsx
src/components/chart/RiskScoreBarChart/index.tsx
src/components/chart/RiskScorePieChart/index.tsx

update risk signal charts to check for permission
[Ticket]()
storybook

feat: update risk signal charts to check for permission

---

src/components/form/OneClickForm/components/validations/fragments/credentials.ts

Removed duplicated SSN schema and replaced it with the fixed schema version.
- 1b71c21: fix(ssn): remove duplicated schema and use the fixed one
Tested locally for verification.

fix(ssn): remove duplicated schema and use the fixed one

---

src/components/form/OneClickForm/components/CredentialsDisplay/components/EditModeButton.tsx

Fix position issue in UI component
- 9b0f2c1: fix: add correct position

fix: add correct position

---

package-lock.json
package.json
src/components/CredentialRequestsEditor/components/DataFieldAccordion.tsx
src/components/CredentialRequestsEditor/components/DataFieldMandatory.tsx
src/components/CredentialRequestsEditor/types/form.ts
src/components/CredentialRequestsEditor/types/mandatoryEnum.ts
src/components/CredentialRequestsEditor/utils/buildDataFieldValue.ts
src/components/form/OneClickForm/components/CredentialsDisplay/types.ts
src/components/form/OneClickForm/components/CredentialsDisplay/utils/isRequiredCredentialDisplayInfo.ts
src/components/form/OneClickForm/components/CredentialsDisplay/utils/makeCredentialDisplayInfoList.ts
src/components/form/OneClickForm/types/request.ts

Implement constants repository
Implement constants repository

Implement constants repository

---

src/components/CredentialRequestsEditor/CredentialRequestsEditor.context.tsx
src/components/CredentialRequestsEditor/components/CredentialRequestsField.tsx
src/components/CredentialRequestsEditor/components/DataFieldAccordion.tsx
src/components/CredentialRequestsEditor/components/DataFieldMandatory.tsx
src/components/CredentialRequestsEditor/components/DataFieldMulti.tsx
src/components/CredentialRequestsEditor/components/DataFieldOptionType.tsx
src/stories/components/CredentialRequestsEditor.stories.tsx

Update default credential requests behavior
Created new story and tested locally

Update default credential requests behavior

---

src/components/CredentialRequestsEditor/CredentialRequestsEditor.context.tsx
src/components/CredentialRequestsEditor/components/CredentialRequestsField.tsx
src/components/CredentialRequestsEditor/components/DataFieldAccordion.tsx
src/components/CredentialRequestsEditor/components/DataFieldMandatory.tsx
src/components/CredentialRequestsEditor/components/DataFieldOptionType.tsx
src/components/CredentialRequestsEditor/types/form.ts
src/components/CredentialRequestsEditor/types/mandatoryEnum.ts
src/components/CredentialRequestsEditor/types/sdk.ts
src/components/CredentialRequestsEditor/utils/buildDataFieldValue.ts
src/components/form/OneClickForm/components/CredentialsDisplay/types.ts
src/components/form/OneClickForm/components/CredentialsDisplay/utils/isRequiredCredentialDisplayInfo.ts
src/components/form/OneClickForm/components/CredentialsDisplay/utils/makeCredentialDisplayInfoList.ts
src/stories/components/CredentialRequestsEditor.stories.tsx

Revert constants use
Revert constants use

Revert constants use

---

package-lock.json
package.json
src/components/form/OneClickForm/components/CredentialsDisplay/types.ts
src/components/form/OneClickForm/components/CredentialsDisplay/utils/isRequiredCredentialDisplayInfo.ts
src/components/form/OneClickForm/components/CredentialsDisplay/utils/makeCredentialDisplayInfoList.ts

Remove constants package dependency and fix imports
local and running npm run build

Remove constants package dependency and fix imports

---

src/components/form/PrettyPhoneInput.tsx
src/stories/components/form/PrettyPhoneInput.stories.tsx
src/utils/color/index.ts

Enhanced the PrettyPhoneInput component with dynamic animations and improved error state support for a better user experience.
- 29611c4: feat: enhance PrettyPhoneInput with dynamic animations and error state support

feat: enhance PrettyPhoneInput with dynamic animations and error state support

---

src/components/chart/MonthlySignupsOverviewTable/MonthlySignupsOverviewTable.tsx
src/components/chart/MonthlySignupsOverviewTable/MonthlySignupsOverviewTableDataMapper.ts

Add risk signal column to monthly signups overview table
- Update typing
- add optional risk signal
local

feat: Add risk signal column to monthly signups overview table

---

src/components/chart/MonthlySignupsOverviewTable/MonthlySignupsOverviewTable.tsx
src/components/chart/OneClickOverTimeChart/OneClickTimeSeriesDataMapper.ts
src/components/chart/SignupBigNumbers/SignupBigNumbersMapper.ts

Update character for empty values on the monthly table
fixed some types
updated character
local storybook

Update character for empty values on monthly table

---

.github/workflows/auto-approve.yml

Add auto-approve workflow for PRs with approve label

Add auto-approve workflow for PRs with approve label

---

package-lock.json
package.json
src/components/buttons/ExportToPdfButton.tsx
src/components/buttons/index.ts
src/stories/components/buttons/ExportToPdfButton.stories.tsx

add ExportToPdfButton component with PDF generation functionality
local

feat: add ExportToPdfButton component with PDF generation functionality

---

src/components/form/OneClickForm/components/CredentialsDisplay/components/EditModeButton.tsx
src/components/form/OneClickForm/components/CredentialsDisplay/utils/transformToFormObject.ts
src/components/form/OneClickForm/components/DataField/DataFieldAtomic.tsx
src/components/form/OneClickForm/components/DataField/DataFieldCheckbox.tsx
src/components/form/OneClickForm/components/DataField/DataFieldComposite.tsx
src/components/form/OneClickForm/components/DataField/DataFieldHeader/HeaderSelect/index.tsx
src/components/form/OneClickForm/components/DataField/DataFieldHeader/HeaderSelect/styles.ts
src/components/form/OneClickForm/components/DataField/DataFieldInputLabel.tsx
src/components/form/OneClickForm/components/DataField/DataFieldLabel.tsx
src/components/form/OneClickForm/components/DataField/formats/DataFieldImage.tsx
src/components/form/OneClickForm/components/DataField/inputs/DataFieldImageInput.tsx
src/components/form/OneClickForm/components/DataField/utils/getCredentialLabel.ts
src/components/form/OneClickForm/constants/credentialTypes.ts
src/stories/components/form/OneClickForm.stories.tsx

This PR fixes form layout and alignment issues in OneClickForm components and improves image field UI with GovernmentIdDocumentImage support.
- f62a662: feat: improve image field UI and add GovernmentIdDocumentImage support
- 84c9bf5: fix: Fix form layout and alignment issues in OneClickForm components

fix: Form UI and layout issues in OneClickForm components

---

package-lock.json
package.json
src/components/buttons/ExportToPdfButton.tsx
src/components/buttons/index.ts
src/components/form/TimezoneInput/timezones.ts
src/stories/components/buttons/ExportToPdfButton.stories.tsx

fix animation issues with pdf button, transform it into an IconButton and remove invalid timezone option
local

fix: add ExportToPdfButton component with PDF generation functionality

---

package-lock.json
package.json
src/components/buttons/OriginalButton.tsx
src/components/buttons/index.ts
src/components/dialog/Dialog.tsx
src/components/dialog/index.ts
src/components/form/RadioOption.tsx
src/components/form/index.ts
src/components/index.ts
src/stories/components/buttons/OriginalButton.stories.tsx
src/stories/components/dialog/Dialog.stories.tsx
src/stories/components/form/RadioOption.stories.tsx
src/styles/theme.ts
src/utils/color/index.ts
src/utils/index.ts
src/utils/makeGoogleFont.ts

add Dialog, OriginalButton and RadioOption components for the demo
local and with the demo

Dialog, OriginalButton and RadioOption components for the demo

---

src/styles/theme.ts

This PR adds a shadow effect to MUI buttons when they are focused, enhancing the UI feedback for users.
- 70eb7a6: feat(theme): add shadow effect to focused MUI buttons
Locally tested by verifying the shadow effect appears when MUI buttons receive focus.

feat(theme): add shadow effect to focused MUI buttons

---

package-lock.json
package.json
src/components/CredentialRequestsEditor/components/DataFieldAccordion.tsx
src/components/CredentialRequestsEditor/types/sdk.ts
src/stories/components/CredentialRequestsEditor.stories.tsx

refactor: update SdkIntegrationType to use core-service-v2 package
refactor: update SdkIntegrationType to use core-service-v2 package
Tested locally

refactor: update SdkIntegrationType to use core-service-v2 package

---

src/components/form/OTPInput.tsx
src/styles/theme.ts

Enhances OTP input component with improved accessibility and user experience features, including better keyboard navigation, autofill support, and focus management.
- Added support for autofill functionality (particularly from iOS/Android devices)
- Implemented arrow key navigation between OTP input fields
- Improved focus management and keyboard interaction
- Added proper tabIndex attributes for better keyboard accessibility
- Enhanced handling of input values to support both manual input and autofill
- Refined button focus styles in theme to be more specific to contained buttons
- Removed redundant code and dependencies
N/A

Enhance OTP input with accessibility and UX improvements

---

package-lock.json
package.json
src/components/form/OneClickForm/components/CredentialsDisplay/CredentialsDisplay.tsx
src/components/form/OneClickForm/components/CredentialsDisplay/components/EditModeButton.tsx
src/components/form/OneClickForm/components/DataField/DataFieldAtomic.tsx
src/components/form/OneClickForm/components/DataField/DataFieldComposite.tsx
src/components/form/OneClickForm/components/DataField/DataFieldHeader/HeaderSelect/index.tsx
src/components/form/OneClickForm/components/DataField/DataFieldLabel.tsx
src/components/form/OneClickForm/components/DataField/DataFieldRootStack.tsx
src/components/form/OneClickForm/components/DataField/formats/DataFieldText.tsx

This PR enhances form component accessibility by adding ARIA attributes and semantic HTML elements, while also fixing edit button positioning and updating the react-hook-form version constraint to ensure compatibility.
- Added version constraint for react-hook-form (`>=7.52.1 <=7.53.2`) to prevent installing an higher version with breaking changes
- Repositioned edit button in CredentialsDisplay component
- Added `aria-hidden="true"` to Edit icon for screen readers
- Added proper ARIA roles and labels to form components
- Improved component semantics by using `section` elements and `label` instead of `span`
- Enhanced keyboard navigation with appropriate tabIndex properties
- Added descriptive aria-labels to improve screen reader experience
These changes can be tested by navigating …

Enhance form accessibility and fix UI component issues

---

src/components/form/OneClickForm/components/DataField/inputs/DataFieldAddressInput/hook.ts
src/components/form/OneClickForm/components/DataField/inputs/DataFieldAddressInput/index.tsx

Improves performance of the Address Input component by optimizing rendering and refactoring the input handling logic.
- Created a separate type definition `DataFieldAddressInputReturn` for better code organization
- Refactored input handling to prevent excessive validations:
- Modified `handleInputChange` to only update the input value without triggering validation on every keystroke
- Added a dedicated `handleClear` function to properly handle input clearing
- Implemented debounced validation pattern to reduce unnecessary processing
- Added `disableInjectingGlobalStyles: true` to the TextField InputProps to prevent performance issues with MUI global styles injection (referenced GitHub issue #38314)
N/A

Optimize Address Input component performance and validation

---

src/components/text-to-signup/magic-button.tsx
src/hooks/index.ts
src/hooks/useGoogleFont.ts
src/stories/components/text-to-signup/TTSMagicButton.stories.tsx

Summary
======
This PR adds Google Fonts support to the TTSMagicButton component, allowing customization of the button's font family. It also includes a new useGoogleFont hook for dynamically loading Google Fonts.
Changes
======
- Added new `useGoogleFont` hook to handle Google Font loading and CSS injection
- Enhanced TTSMagicButton component with font family customization
- Added new props to TTSMagicButton: `fontFamily` and `enableGoogleFontLoad`
- Improved image generation to properly include custom fonts
- Added comprehensive JSDoc documentation
- Exported useGoogleFont hook from the hooks index
- Modified TTSMagicButton story to disable Google Fonts loading by default
Testing
======
The component can be tested by setting the `fontFamily` prop to a valid Google Font family name and …

Add Google Fonts support to TTSMagicButton component
