src/components/form/PhoneInput.tsx
The validation was only validating us numbers. By using this fragment we could use different numbers if we wanted
[Ticket]()
=> fix: change phone validation to allow numbers from different countries

src/components/form/SSNInput.tsx, src/stories/components/form/SSNInput.stories.ts
feat: make clear adornment optional in ssn input by adding a prop called shouldHaveCloseAdornment
[Ticket]()
also fixed ssn stories. It wasn't passing the proper args
using stories
=> feat: make clear adornment optional in ssn input

src/components/form/DateInput.tsx, src/components/form/InputMask.tsx, src/stories/components/form/DateInput.stories.ts
Fix date input disabled attribute
[Ticket]()
just moved the disabled attribute to the input mask, its right place
locally with storybook
=> fix: Fix date input disabled attribute

src/components/form/OTPInput.tsx
Fix call stack error when blur event is called right before focus.
[Ticket]()
- updated otp input
Locally.
=> fix: remove blur causing maximum call stack error, blur on full otp input

src/components/Snackbar/index.tsx
Remove persist option from Snackbar enqueue function, as this is not a valid option
[Ticket]()
=> fix: remove persist option from Snackbar enqueue function

src/components/form/OTPInput.tsx
Fixes bad setState captured in the Dashboard project when pasting the OTP, causing a setState to blur the input in the MUI core package.
[Ticket]()
- updated OTPInput
Locally.
=> fix: add form control to input base to avoid bad setState

src/components/chart/SeriesChartLegend/index.tsx
Fixed renderer to have key prop at top react element.
[Ticket]()
- moved key prop up
Locally.
=> fix: add key prop to top react element renderer

src/components/chart/SeriesPercentageChart/index.tsx, src/components/chart/index.ts, src/stories/components/chart/SeriesPercentageChart.stories.tsx, vite.config.mts
Implemented a new 1-Click Percentage Over Time chart component to visualize success and creation rates, with brand-specific filtering and proper percentage calculations.
[Ticket]()
- Created new [OneClickPercentageOverTimeChart](cci:1://file:///Users/iagormoraes/Desktop/projects/UnumID/mission-control-client/src/features/metrics/components/OneClickPercentageOverTimeChart/index.tsx:60:0-229:1) component with:
- Single brand selection filter
- Stacked area chart showing Success and Created percentages
- Proper percentage calculations based on total values per period
- Loading and empty states handling
- Last updated timestamp display
- Enhanced [BrandFilterInput](cci:1://file:///Users/iagormoraes/Desktop/projects/UnumID/mission-control-client/src/features/metrics/components/BrandFilterInput/ …
=> feat: add series percentage chart

package-lock.json, package.json, src/components/chart/SeriesPercentageChart/index.tsx, src/stories/components/chart/SeriesPercentageChart.stories.tsx
Enhanced SeriesPercentageChart component to support total values and improved data visualization with better percentage calculations and tooltips.
[Ticket]()
- Added support for total values in series data through `isTotal` flag in KeyValue interface
- Improved data structure to handle both absolute values and percentages
- Enhanced tooltip formatting to show absolute values and percentages
- Fixed division by zero issues in percentage calculations
- Added proper type handling for string and number values in chart data
- Improved visual styling with:
- Configurable fill opacity (0.6)
- Theme-based cursor color
- Removed stack offset for better data representation
- Restructured data processing to:
- Calculate percentages based on total values
- Store both absolute and relative values
- …
=> fix: change how chart displays each serie to an absolute area

src/components/chart/SimpleBarChart/index.tsx, src/components/chart/index.ts, src/stories/components/chart/SimpleBarChart.stories.tsx
Added a new SimpleBarChart component that provides a responsive and customizable bar chart implementation using Recharts. The component supports styling through MUI's sx prop and allows for axis customization.
[Ticket]()
- Created new [SimpleBarChart](cci:1://file:///Users/iagormoraes/Desktop/projects/UnumID/shared-ui-elements/src/components/chart/SimpleBarChart/index.tsx:20:0-58:1) component with the following features:
- Responsive design that adapts to container size
- Customizable bar colors
- Configurable X and Y axis properties through props
- Built with Recharts for smooth rendering
- Added Storybook documentation and examples
- Default story showcasing basic usage
- CustomStyling story demonstrating axis customization
- Updated chart barrel file to export the new component …
=> feat: add simple bar chart

src/components/chart/SimpleBarChart/index.tsx, src/stories/components/chart/SimpleBarChart.stories.tsx
Added support for multiple series in SimpleBarChart component with stacked bars functionality and enhanced reference lines with front/back positioning capability.
[Ticket]()
- Added support for multiple data series in SimpleBarChart component with automatic stacking
- Each series can have its own color and data key
- Bars from different series are automatically stacked when rendered
- Enhanced reference lines functionality
- Added ability to position reference lines in front or behind bars using `isFront` property
- Split reference lines rendering to support proper z-index layering
- Updated storybook examples to demonstrate new features
- Added examples with multiple series
- Showcased reference lines positioning capabilities
Locally.
=> Serie bar chart support

src/components/chart/SimpleBarChart/index.tsx, src/components/chart/shared.ts, src/stories/components/chart/SimpleBarChart.stories.tsx
Enhanced SimpleBarChart component with improved props structure, shared default props, and added more control over tooltip and axis customization. This change improves component reusability and customization capabilities.
[Ticket]()
- Refactored SimpleBarChart props structure for better consistency
- Renamed `xAxisProps` and `yAxisProps` to `xAxis` and `yAxis` respectively
- Moved `xAxisDataKey` into `xAxis.dataKey` for better prop organization
- Added new props for tooltip and bar customization
- Created shared default props for chart components
- Added [shared.ts](cci:7://file:///Users/iagormoraes/Desktop/projects/UnumID/shared-ui-elements/src/components/chart/shared.ts:0:0-0:0) with default props for chart, x-axis, and y-axis
- Extracted common styling into reusable configurations
- …
=> add tooltip props

src/components/chart/ErrorCodesChart/index.tsx, src/components/chart/index.ts, src/stories/components/chart/ErrorCodesChart.stories.tsx
Added a new ErrorCodesChart component that visualizes error code occurrences using a bar chart, with an unhealthy threshold reference line and customizable styling options.
[Ticket]()
- Created new [ErrorCodesChart](cci:1://file:///Users/iagormoraes/Desktop/projects/UnumID/shared-ui-elements/src/components/chart/ErrorCodesChart/index.tsx:22:0-92:1) component that displays error code frequencies
- Added comprehensive documentation and TypeScript types for the component
- Created Storybook stories with multiple variants (Default, NoData, SingleError)
- Component features:
- Dynamic bar generation based on error code data
- Unhealthy threshold reference line at y=100
- Custom styling through MUI's sx prop
- Tooltip customization showing "Total" as label
- Theme-based error color for bars
- …
=> feat: add error code chart

src/components/chart/RiskScoreBarChart/index.tsx, src/components/chart/SimpleBarChart/index.tsx, src/stories/components/chart/RiskScoreBarChart.stories.tsx
Created RiskScoreBarChart component that displays risk scores from 0 to 1000 with visual indicators for Allowed (0-299), Flagged (300-600), and Blocked (600+) ranges. The component aggregates score data and displays it using SimpleBarChart with appropriate styling and tooltips.
[Ticket]()
- Created new RiskScoreBarChart component that:
- Accepts an array of objects containing risk score counts
- Aggregates scores and displays them in a bar chart format
- Shows full range from 0 to 1000 with appropriate scaling
- Uses theme colors for bars and reference areas
- Enhanced SimpleBarChart component to support ReferenceArea elements
- Added visual indicators for risk ranges:
- 0-299: Allowed (transparent)
- 300-600: Flagged (warning light)
- 600+: Blocked (error light)
- Improved tooltip …
=> feat: add risk score bar chart

src/components/chart/SimpleBarChart/index.tsx
Fixed circular reference issues in SimpleBarChart by improving key generation for reference elements.
[Ticket]()
- Updated key prop to avoid circular reference
Locally.
=> fix: replace json stringify with label uniqueness falling back to index

src/components/chart/PieChart/index.tsx, src/components/chart/PieChart/renderActiveShape.tsx, src/components/chart/RiskScorePieChart/index.tsx, src/stories/components/chart/PieChart.stories.tsx
Added new `allActive` prop to PieChart component that enables displaying details for all pie slices simultaneously. This enhancement improves data visualization by allowing users to see all slice details at once without needing to hover over individual slices.
[Ticket]()
- Added new `allActive` prop to PieChart component interface
- Modified PieChart component to support displaying multiple active shapes simultaneously
- Updated renderActiveShape to handle multiple active states:
- Added conditional rendering for center text to prevent overlapping
- Adjusted label positioning and spacing for better readability
- Added `allActive` prop to control center text visibility
- Updated RiskScorePieChart to use the new `allActive` prop by default
Locally.
=> feat: add allActive prop display pie detail

src/components/chart/PieChart/index.tsx
Added new `allActive` prop to PieChart component that enables displaying details for all pie slices simultaneously, while properly handling hidden slices. This enhancement improves data visualization by allowing users to see all active slice details at once, excluding any hidden or zero-value slices.
[Ticket]()
- Added new `allActive` prop to PieChart component interface
- Modified PieChart component to support displaying multiple active shapes simultaneously:
- Added filter to exclude zero-value slices from active indices
- Updated renderActiveShape to handle multiple active states
- Added conditional rendering for center text to prevent overlapping
- Adjusted label positioning and spacing for better readability
- Updated RiskScorePieChart to use the new `allActive` prop by default …
=> fix: omit hidden slices info

src/components/chart/PieChart/index.tsx
Fixes allActive to correctly omit the info when some of the slices are not selected.
[Ticket]()
- Fixed `activeIndex` for `allActive`to keep index reference
Locally.
=> fix: filter out if value is zero keeping index reference

src/components/chart/ReasonCodesChart/index.tsx, src/components/chart/index.ts, src/stories/components/chart/ReasonCodesChart.stories.tsx
Added a new ReasonCodesChart component based on the ErrorCodesChart to visualize reason code occurrences. The component uses OCR prefixed codes and maintains visual consistency with other chart components.
[Ticket]()
From commit [d21217c]:
- Created new ReasonCodesChart component using the same structure as ErrorCodesChart
- Added corresponding story with examples of different reason code scenarios
- Used OCR prefix for reason codes
- Implemented error color scheme for consistency with other charts
- Added component to the chart exports
Locally.
=> feat: Add reason code chart

src/components/form/OneClickForm/components/DataField/DataFieldCheckbox.tsx, src/components/form/OneClickForm/contexts/one-click-form-options.context.tsx, src/stories/components/form/OneClickForm.stories.tsx
Added support for optional selectable credentials in the OneClickForm component, enhancing flexibility in credential selection workflows.
[Ticket]()
- **93a3f11**: Added functionality to make selectable credentials optional in the form
- Updated OneClickForm component to handle optional selectable fields
- Modified form validation logic to accommodate optional selections
Locally.
=> feat: make selectable credentials optional

src/components/form/OneClickForm/components/CredentialsDisplay/utils/getLastPathName.ts, src/components/form/OneClickForm/components/CredentialsDisplay/utils/index.ts, src/components/form/OneClickForm/components/DataField/inputs/DataFieldSelectInput.tsx, src/components/form/OneClickForm/components/DataField/inputs/DataFieldTextInput.tsx, src/components/form/OneClickForm/contexts/one-click-form-options.context.tsx, src/components/form/OneClickForm/hooks/useCanFillByQueryParam.ts, src/stories/components/form/OneClickForm.stories.tsx
Added a new feature to OneClickForm that allows form fields to be auto-filled by URL query parameters. This provides a more flexible way to pre-populate form fields through URL parameters while maintaining control over which fields can be auto-filled.
[Ticket]()
From commit [0cfacb0]():
- Added `fillEmptyByQueryParam` option to OneClickFormOptions that accepts an array of field names or '*' to control which fields can be auto-filled
- Created useCanFillByQueryParam hook to manage field autofill permissions
- Updated DataFieldTextInput and DataFieldSelectInput to respect the new option
- Added validation to only autofill fields that are empty and explicitly allowed
- Added example usage in storybook to demonstrate the feature
Key implementation details:
- Fields will only be auto-filled if …
=> feat: add fillEmptyByQueryParam option to OneClickForm

src/components/CredentialRequestsEditor/utils/buildDataFieldValue.ts, src/stories/components/CredentialRequestsEditor.stories.tsx
Fix issue with [buildDataFieldValue](cci:1://file:///Users/iagormoraes/Desktop/projects/UnumID/shared-ui-elements/src/components/CredentialRequestsEditor/utils/buildDataFieldValue.ts:80:0-112:1) where nested schema types were being incorrectly included in the parent list. Now child schemas like `CurrencyCredential` and `AmountCredential` will only appear under their direct parent `AnnualIncomeCredential`, not at the root level.
[Ticket]()
- aece138: Refactored [extractTypes](cci:1://file:///Users/iagormoraes/Desktop/projects/UnumID/shared-ui-elements/src/components/CredentialRequestsEditor/utils/buildDataFieldValue.ts:36:0-84:1) function to properly handle schema hierarchy:
- Only collect direct children of each schema
- Stop traversing when finding a schema with `$id`
- Prevent nested …
=> fix: refactor buildDataFieldValue to prevent child of child item schema to be included in the parent list

src/hooks/index.ts, src/hooks/useNavigatorOnline.ts, src/hooks/useResizeObserver.ts, src/stories/hooks/useNavigatorOnline.stories.tsx, src/stories/hooks/useResizeObserver.stories.tsx
Added two new hooks: `useNavigatorOnline` for tracking browser's online status and `useResizeObserver` for observing element dimensions. Both hooks are SSR-compatible and use React 18's `useSyncExternalStore` for concurrent rendering support.
[Ticket]()
From commit [ede35be]():
- Added `useNavigatorOnline` hook with SSR support and comprehensive documentation
- Added `useResizeObserver` hook with SSR support and comprehensive documentation
- Created Storybook stories for both hooks with interactive demos
- Added hooks to the main exports in `index.ts`
1. Run Storybook and test `useNavigatorOnline`:
- Toggle network connection to verify online/offline state changes
- Use browser DevTools to simulate offline mode
- Verify SSR compatibility by disabling JavaScript
2. Test …
=> feat: add navigator online state and resize observer hook

src/utils/wrapPromise.ts, vite.config.mts
Fix type inference in [wrapPromise](cci:1://file:///Users/iagormoraes/Desktop/projects/UnumID/shared-ui-elements/src/utils/wrapPromise.ts:2:0-16:1) utility by updating the error type default to `object` and adding the utility to the exports.
[Ticket]()
- [eb4c5ec] Fix type inference in [wrapPromise](cci:1://file:///Users/iagormoraes/Desktop/projects/UnumID/shared-ui-elements/src/utils/wrapPromise.ts:2:0-16:1) by changing the default error type from `unknown` to `object`
- [5e53d39] Add [wrapPromise](cci:1://file:///Users/iagormoraes/Desktop/projects/UnumID/shared-ui-elements/src/utils/wrapPromise.ts:2:0-16:1) utility to the exports in [vite.config.mts](cci:7://file:///Users/iagormoraes/Desktop/projects/UnumID/shared-ui-elements/vite.config.mts:0:0-0:0)
- Test the …
=> Update wrap promise type

src/components/chart/ErrorCodesChart/index.tsx, src/components/chart/ReasonCodesChart/index.tsx
Prevent the reference lines from being drawn outside the canvas.
[Ticket]()
- fixed reason codes
- fixed error codes
Locally.
=> fix: increase threshold and make an offset to prevent being overflown

src/components/chart/MonthlySignupsOverviewTable/MonthlySignupsOverviewTable.tsx, src/components/chart/MonthlySignupsOverviewTable/MonthlySignupsOverviewTableDataMapper.ts, src/stories/components/chart/MonthlySignupsOverviewTable.stories.tsx
Added brandUuid to MonthlySignupsOverviewTable data to prevent duplicate keys in table rows rendering, improving React's reconciliation process.
[Ticket]()
- [317a8af] Fixed duplicate key issue in MonthlySignupsOverviewTable:
- Added `brandUuid` to table data interface and mapper
- Updated table row key to use `brandUuid` instead of brand name
- Updated stories mock data to include `brandUuid`
- Verify table renders correctly with the new unique keys
- Check that rows are properly identified and updated when data changes
- Ensure no console warnings about duplicate keys
- Confirm table functionality remains unchanged with the new key structure
=> fix: prevent duplicated key to render

src/components/chart/SeriesChartLegend/index.tsx
Fixed React key warning in SeriesChartLegend by using a combination of UUID and value to ensure unique keys for each legend entry.
[Ticket]()
- [01e46e5] Fixed duplicate key warning in SeriesChartLegend:
- Updated Grid2 component key to use both UUID and value from entry payload
- Changed key format from `item-${entry.value}` to `item-${entry.payload.uuid}-${entry.value}`
- Improved React's reconciliation process for legend items
- Verify legend renders correctly with the new unique keys
- Check React console for any key-related warnings
- Ensure legend animation and interaction behavior remains unchanged
- Test with multiple data series to confirm unique key generation
=> fix: prevent duplicated key warning

src/components/form/DateInput/index.tsx, src/stories/components/form/DateInput.stories.tsx
Added support for default selected date in DateInput component and improved date handling with UTC. Also includes fixes for date validation and selection behavior.
[Ticket]()
- 031b155: Added default selected date picker support with the following changes:
- Added `pickerDefaultSelectedDate` prop to DateInput component
- Improved date handling using UTC methods
- Enhanced date validation and selection logic
- Added new story for CustomDefaultSelectedDatePicker
- 03426f8: Removed debug logging
- Test the new CustomDefaultSelectedDatePicker story in Storybook
- Verify date selection with default date (08/01/1989)
- Verify date validation for min (1900) and max (current) dates
- Test UTC date handling across different timezones
=> Feat(DateInput): support default selected date picker

.storybook/preview.tsx, src/components/BrandFilterInput/index.tsx
don't show "select live brands" under any grouping and change default storybook viewport to desktop
[Ticket]()
storybook
=> fix: don't show "select live brands" under any grouping

src/components/form/OneClickForm/components/CredentialsDisplay/CredentialsDisplay.tsx, src/components/form/OneClickForm/components/CredentialsDisplay/CredentialsDisplayContext.tsx, src/components/form/OneClickForm/components/CredentialsDisplay/utils/extractChildrenFromCredentialFieldSet.ts, src/components/form/OneClickForm/components/CredentialsDisplay/utils/hasMandatoryCredentialRequests.ts, src/components/form/OneClickForm/components/CredentialsDisplay/utils/index.ts, src/components/form/OneClickForm/components/DataField/inputs/DataFieldDateInput.tsx, src/stories/components/form/OneClickForm.stories.tsx
Improves form field behavior by fixing validation triggers, handling select events properly, and automatically setting edit mode based on mandatory credentials.
- 1b1df1c feat: automatically set edit mode based on mandatory credentials
- b528581 fix: handle select event on change value event
- 561650a fix: trigger validation on schema update
Locally tested with the OneClickForm component in Storybook to verify all form fields behave correctly, especially with the new Places API integration.
=> Fix form fields behavior and update Places API integration

src/components/chart/OneClickOverTimeChart/OneClickOverTimeChart.tsx
Make timezone optional in OneClickOverTimeChart filter interface
=> Make timezone optional in OneClickOverTimeChart filter interface

src/components/form/OneClickForm/components/DataField/DataFieldHeader/HeaderSelect/index.tsx, src/components/form/OneClickForm/components/DataField/DataFieldHeader/HeaderSelect/utils/renderInstance.tsx
Fixed issue with event propagation in HeaderSelect component and removed disabled/readonly states.
- 342a9cb - fix: prevent event propagation and remove disabled/readonly states in HeaderSelect
=> fix: prevent event propagation and remove disabled/readonly states in HeaderSelect

src/components/form/DateInput/index.tsx, src/components/form/OneClickForm/components/CredentialsDisplay/CredentialsDisplayItemContext.tsx, src/components/form/OneClickForm/components/CredentialsDisplay/components/EditModeButton.tsx, src/components/form/OneClickForm/components/CredentialsDisplay/utils/index.ts, src/components/form/OneClickForm/components/CredentialsDisplay/utils/isSomeFieldInputAllowed.ts, src/components/form/OneClickForm/components/CredentialsDisplay/utils/makeCredentialDisplayInfoList.ts, src/components/form/OneClickForm/components/DataField/DataFieldAtomic.tsx, src/components/form/OneClickForm/components/DataField/DataFieldClearAdornment.tsx, src/components/form/OneClickForm/components/DataField/DataFieldHeader/HeaderSelect/index.tsx, src/components/form/OneClickForm/components/DataField/DataFieldRootStack.tsx, src/components/form/OneClickForm/components/DataField/index.ts, src/components/form/OneClickForm/components/DataField/inputs/DataFieldAddressInput/index.tsx, src/components/form/OneClickForm/components/DataField/inputs/DataFieldDateInput.tsx, src/components/form/OneClickForm/components/DataField/inputs/DataFieldImageInput.tsx, src/components/form/OneClickForm/components/DataField/inputs/DataFieldPhoneInput.tsx, src/components/form/OneClickForm/components/DataField/inputs/DataFieldSSNInput.tsx, src/components/form/OneClickForm/components/DataField/inputs/DataFieldSelectInput.tsx, src/components/form/OneClickForm/components/DataField/inputs/DataFieldTextInput.tsx, src/stories/components/form/OneClickForm.stories.tsx
This PR implements the ability to control whether credential fields can be edited by users based on an "allowUserInput" property in credential requests.
- feat: Implement input disabled state based on allowUserInput credential request property (6728641)
- refactor: Refactor DataField header and select components for better event handling (3b886e0)
- chore: Remove unused component (94de56f)
Locally for Testing. The OneClickForm component can be tested with various credential configurations to verify that fields are properly enabled/disabled based on the allowUserInput property.
=> feat: Implement credential field user input control

src/components/form/OneClickForm/components/CredentialsDisplay/CredentialsDisplay.tsx
Added margin top spacing to the DataFieldRootStack component to prevent the label from being clipped.
- fix: Add margin top spacing to DataFieldRootStack component to prevent from clipping label (21e4b71)
=> fix: Add margin top spacing to DataFieldRootStack component to prevent from clipping label

package-lock.json, package.json, src/components/animation/motions.ts
This PR lowers the peer dependency requirement for framer-motion from >=11.15.0 to >=11.11.1 and simplifies motion component exports by using type assertions to prevent unknown build errors.
- Reduced the minimum version requirement for framer-motion from >=11.15.0 to >=11.11.1 in both package.json and package-lock.json
- Removed specific type imports from '@mui/material' that were no longer needed
- Changed motion component implementations to use `as any` type assertion instead of explicit ForwardRefExoticComponent typing
- Applied consistent `forwardMotionProps: false` option to all motion components
The changes can be tested by importing and using motion components with the lower framer-motion version to ensure they render correctly.
=> Lower motion peer dependency and fix component type exports

src/components/animation/motions.ts
Fix usage of framer-motion API by replacing deprecated `motion.create` with `motion` function for all Material-UI component animations.
- Updated all motion component declarations to use `motion()` instead of `motion.create()`
- Changed implementation for MotionBox, MotionStack, MotionTbody, MotionTableRow, MotionTableCell, MotionTypography, and MotionButton components
- Maintained the `forwardMotionProps: false` configuration for all components
N/A - This change should be tested by verifying that all animated components still function correctly in their respective contexts.
=> Fix framer-motion API usage by replacing deprecated motion.create

src/components/animation/motions.ts
Fix type casting in motion components by simplifying the casting from `React.ComponentType<any>` to just `any`.
- Simplified type casting in all motion component definitions (MotionBox, MotionStack, MotionTbody, MotionTableRow, MotionTableCell, MotionTypography, and MotionButton)
- Changed from `motion(Component as React.ComponentType<any>, {` to `motion(Component as any, {` for all components
- This change maintains the same functionality while using a simpler type casting approach
N/A
=> Simplify type casting in motion components

src/components/form/RadioOption.tsx
Add proper disabled state handling for RadioOption component
- Added `disabled` prop to the Radio component
- Enhanced Stack component styling to properly handle disabled states:
- Added opacity change (0.4) when disabled
- Added pointer-events control to prevent interaction when disabled
- Maintained the cursor style for enabled state
Manual testing can be performed by:
- Adding a RadioOption component with `disabled={true}` prop
- Verifying that the component appears faded and is not interactive
=> Add disabled state handling to RadioOption component

package-lock.json, package.json, vite.config.mts
Add back date picker package as a dependency to prevent rendering errors.
- updated dependency in package.json
- updated vite configuration
Locally with npm pack
=> fix: add datepicker as dependency to prevent render error

src/components/CredentialRequestsEditor/components/DataFieldOptionType.tsx
Switch from blacklist to whitelist approach in credential requests editor, explicitly defining allowed credential types.
- Changed the filtering logic in `DataFieldOptionType.tsx` from a blacklist approach to a whitelist approach
- Added explicit list of allowed credential types (address-related, name-related, and other personal credentials)
- This ensures only specific credential types can be selected in the editor
N/A
=> Switch credential requests editor from blacklist to whitelist approach

src/components/form/AddressInput/autofill.hook.ts, src/components/form/AddressInput/context.tsx, src/components/form/AddressInput/index.tsx, src/stories/components/form/AddressInput.stories.tsx
This PR makes the Google Places service response format agnostic by changing the return types from `Promise<Response>` to `Promise<unknown>` and updating the implementation to handle parsed data directly.
- Modified the return type of Google Places API functions from `Promise<Response>` to `Promise<unknown>` in type definitions
- Updated the autofill hook to handle direct data responses rather than having to parse Response objects
- Refactored the implementation in stories to return parsed data (typed objects) instead of Response objects
- Improved error handling in the Google Places API integration
Storybook and Dashboard client.
=> Make Google Places service response format agnostic

src/components/form/OneClickForm/components/DataField/inputs/DataFieldAddressInput/hook.ts
Added missing `disabled` property to the DataFieldAddressInputReturn type to fix type-related build issues.
- Added the `disabled: boolean` property to the DataFieldAddressInputReturn type in the DataFieldAddressInput hook file
N/A
=> Add disabled property to DataFieldAddressInputReturn type

src/components/form/OneClickForm/components/DataField/inputs/DataFieldDateInput.tsx
This PR fixes date handling in DataFieldDateInput component by ensuring proper UTC date creation from MM/DD/YYYY format strings instead of relying on implicit date conversion.
- Modified date parsing logic in DataFieldDateInput.tsx to explicitly split date strings by '/' and create UTC dates
- Replaced the post-creation UTC hours adjustment with a direct UTC date creation approach
- Added more descriptive comments about the date parsing process
The changes can be tested by entering various date values in the OneClickForm component's date fields and verifying that the dates are correctly interpreted regardless of the user's timezone.
=> Fix UTC date handling in DataFieldDateInput component

src/components/form/DateInput/index.tsx, src/components/form/OneClickForm/components/CredentialsDisplay/CredentialDisplayContextSkeleton.tsx, src/components/form/OneClickForm/components/CredentialsDisplay/CredentialsDisplayContext.tsx, src/components/form/OneClickForm/components/CredentialsDisplay/utils/hasMandatoryFieldEmpty.ts, src/components/form/OneClickForm/components/CredentialsDisplay/utils/isValidInputCredential.ts, src/components/form/OneClickForm/components/CredentialsDisplay/utils/transformToFormSchema.ts, src/components/form/OneClickForm/components/DataField/inputs/DataFieldAddressInput/hook.ts, src/components/form/OneClickForm/components/DataField/inputs/DataFieldDateInput.tsx, src/components/form/OneClickForm/components/validations/fragments/birthDate.ts, src/components/form/OneClickForm/constants/credentialTypes.ts, src/components/form/OneClickForm/utils/calendarDateFormatter.ts, src/stories/components/form/OneClickForm.stories.tsx, tests/components/form/OneClickForm/components/validations/fragments/birthDate.test.ts, tsconfig.json
Add minimum age validation (18+) to birth date inputs and improve date handling throughout the OneClickForm component.
- Added `minDate` and `maxDate` props to DateInput component for enforcing date ranges
- Implemented validation for birth dates to ensure users are 18+ years old
- Added new validation schemas (`minimumDate1900Schema` and `minimumAge18Schema`) for date validation
- Fixed date handling to consistently use UTC dates to prevent timezone issues
- Added loading skeleton component for credential display
- Updated form validation to show specific error messages for date validation failures
- Added `BirthDateCredential` to credential types constants
- Fixed address input empty value handling with mounted state check
- Improved calendar date formatting to consistently use 'en-US' …
=> Add minimum age validation and improve date handling in OneClickForm

src/components/form/NewOneClickForm/core/shared/us-states.ts
- Removed 'District of Columbia' from the initial list and added it back at the end.
- Added new territories: 'American Samoa', 'Guam', 'Northern Mariana Islands', 'Puerto Rico', and 'United States Minor Outlying Islands'.
- Updated sorting logic for the US_STATES export to sort by state name.
Summary
======
Updated US states enumeration to include US territories and improved sorting logic to alphabetically order states by name instead of by code.
Changes
======
- Reorganized states list by moving 'District of Columbia' from its original position to be grouped with territories
- Added previously missing US territories:
- American Samoa (AS)
- Guam (GU)
- Northern Mariana Islands (MP)
- Puerto Rico (PR)
- United States Minor Outlying Islands (UM)
- Moved 'Virgin Islands' (VI) to be grouped …
=> Add US territories and improve state list alphabetical sorting

src/components/verified/powered-by-verified/index.tsx, src/stories/components/PoweredByVerified.stories.tsx
Summary
======
Added color variants to the PoweredByVerified component, allowing customization through a new variant prop that supports default, green, gray, white, and black color schemes.
Changes
======
- Renamed component file structure (moved to index.tsx within directory)
- Added new variant prop with 5 color options: default, green, gray, white, and black
- Created color mapping systems for both icon and text colors
- Updated component to apply colors based on selected variant
- Enhanced Storybook configuration with proper typing and controls
- Added individual stories for each color variant with appropriate backgrounds
Testing
======
Changes can be verified by viewing each variant in Storybook to confirm proper color application across all variants. The White variant specifically …
=> Add color variants to PoweredByVerified component
